### ISSUE TITLE
Converter which converts from decimal,Binary ,octal,hexadecimal to decimal or octal or hexadecimal or binary

### ISSUE THREAD

**Issue by Sri-vishnu-r1431** [Learn-Write-Repeat/Hacktoberfest-Contribution#12]
Convertor:

A converter which is used to convert from decimal or octal or hexadecimal or binary to decimal or octal or hexadecimal or binary

Kindly Assign it to me under hacktoberfest'21

**Comment by ashutoshkrris** [comment]
Alright @Sri-vishnu-r1431 
But please, make sure you put the Html content in index.html because that is automatically rendered.

**Comment by Sri-vishnu-r1431** [comment]
yes @ashutoshkrris

**Comment by Sri-vishnu-r1431** [comment]
what about contributions.json how do i update it?

**Comment by ashutoshkrris** [comment]
You can update it in the same way, like you did earlier.

**Comment by Sri-vishnu-r1431** [comment]
thanks!! @ashutoshkrris
