### ISSUE TITLE
Assignment Manager

### ISSUE THREAD

**Issue by ShwetKhatri2001** [Learn-Write-Repeat/Hacktoberfest-Contribution#28]
- I want to add a MERN + Multer web app, which manages submissions for assignments for any organization or institution.
- @ashutoshkrris I'd like to work on this issue.

**Comment by ashutoshkrris** [comment]
Yes, please go on!
Also do add a README file documenting what you've done and how you've done it. Use Markdown for the same

**Comment by h2o-Noob** [comment]
- I Want to add a HTML CSS JAVASCRIPT BASED WEBAPP, which can convert numbers to roman numerals.

- @ashutoshkrris i'd like to work on this issue.

**Comment by ashutoshkrris** [comment]
Hey @h2o-Noob 
Please create a separate issue for that

**Comment by h2o-Noob** [comment]
ok sure
