### ISSUE TITLE
Restaurant Website (Frontend)

### ISSUE THREAD

**Issue by ShwetKhatri2001** [Learn-Write-Repeat/Hacktoberfest-Contribution#29]
- I want to add a restaurant website created using HTML, CSS and Bootstrap representing restaurant near my college.
- @ashutoshkrris I'd like to work on this issue.

**Comment by ashutoshkrris** [comment]
Hey @ShwetKhatri2001 
Please work on the previous issue first.
Once that is accepted and merged, I'll assign you this one
