### ISSUE TITLE
Create a Tic Tac Toe Website using Javascript

### ISSUE THREAD

**Issue by SurendarSingh** [Learn-Write-Repeat/Hacktoberfest-Contribution#38]

**Comment by SurendarSingh** [comment]
@ashutoshkrris Can I work on this?

**Comment by ashutoshkrris** [comment]
Yep, go on!

**Comment by And-Rahul** [comment]
Hello, I would like to work on this. Can you assign me this issue?

**Comment by ashutoshkrris** [comment]
@SurendarSingh is already working on this
@And-Rahul If you wish, you can create a separate issue with some different project

**Comment by SurendarSingh** [comment]
@ashutoshkrris yeah I'm working on it, is there a time limit?

**Comment by ashutoshkrris** [comment]
Nope @SurendarSingh , nothing like that
