### ISSUE TITLE
Create Drum Kit Website using Javascript

### ISSUE THREAD

**Issue by SurendarSingh** [Learn-Write-Repeat/Hacktoberfest-Contribution#9]
Create a Drum Kit Website using Javascript which can play different instruments sounds using keyboard press and buttons

**Comment by SurendarSingh** [comment]
@ashutoshkrris Can I work on this?

**Comment by ashutoshkrris** [comment]
Yep sure, @SurendarSingh 
Go ahead!

**Comment by SurendarSingh** [comment]
Can I create multiple issues with unique ideas and work on them or I can work on only 1? @ashutoshkrris

**Comment by ashutoshkrris** [comment]
We recommend working on single issue at a time, so that others also get enough opportunity to contribute.

**Comment by mohit200008** [comment]
Can i work on this issue ???

**Comment by ashutoshkrris** [comment]
Hey @mohit200008 
@SurendarSingh is already working on it.
If you wish, you can create a different issue with unique idea

**Comment by wsameer** [comment]
isn't this part of the front-end certification of freecodecamp?
